HOSTS:
  centos-66-x64:
    roles:
      - master
    platform: el-6-x86_64
    box : puppetlabs/centos-6.6-64-nocm
    box_url : https://vagrantcloud.com/puppetlabs/boxes/centos-6.6-64-nocm
    hypervisor : vagrant
CONFIG:
  type: foss
  #type: pe
  #pe_dir: http://enterprise.delivery.puppetlabs.net/3.8/ci-ready
  #pe_ver: 3.8.0-rc0-463-gc04fc9f
