source "https://rubygems.org"

group :development, :test do
  gem 'puppet', '~> 4.0'
  gem 'facter', '~> 2.3'
  gem 'puppetlabs_spec_helper'
  gem 'rspec-puppet', '~> 2.0'
  gem 'rspec', '2.14'
  gem 'puppet-lint'
  gem 'fakefs', '0.6.7'
  gem 'hocon', '0.9.0'
end
