source ENV['GEM_SOURCE'] || 'https://rubygems.org'

group :development, :test do
  gem 'rake'
  gem 'puppet', '~> 4.0'
  gem 'facter', '~> 2.0'
  gem 'rspec',  '~> 3.0'
  gem 'rspec-puppet',  '~> 2.0'
  gem 'puppetlabs_spec_helper'
end

if File.exists? "#{__FILE__}.local"
  eval(File.read("#{__FILE__}.local"), binding)
end
