source "https://rubygems.org"

group :development, :test do
  gem 'puppet', '~> 3.7.0'
  gem 'facter', '~> 2.3'
  gem 'puppetlabs_spec_helper'
  gem 'rspec-puppet', '~> 1.0'
  gem 'rspec', '2.14'
  gem 'puppet-lint'
  gem 'fakefs', '0.6.7'
end

